//
//  TestData.swift
//  LetsMeet
//
//  Created by Tianid on 16.11.2020.
//  Copyright © 2020 Tianid. All rights reserved.
//

import Foundation


var testPartys = [ Party(name: "Test #1",
                         joiningKey: "123",
                         creationDate: Date(),
                         modifiedDate: Date(),
                         users: [],
                         meetings: testMeets),
                   Party(name: "Test #2",
                         joiningKey: "123",
                         creationDate: Date(),
                         modifiedDate: Date(),
                         users: [],
                         meetings: testMeets),
                   Party(name: "Test #3",
                         joiningKey: "123",
                         creationDate: Date(),
                         modifiedDate: Date(),
                         users: [],
                         meetings: testMeets),
                   Party(name: "Test #4",
                         joiningKey: "123",
                         creationDate: Date(),
                         modifiedDate: Date(),
                         users: [],
                         meetings: testMeets),
                   Party(name: "Test #5",
                         joiningKey: "123",
                         creationDate: Date(),
                         modifiedDate: Date(),
                         users: [],
                         meetings: testMeets)
]


var testMeets = [ Meet(name: "Meet #1",
                       date: Date(),
                       description: "description",
                       address: "address",
                       long: nil,
                       lat: nil,
                       creationDate: Date(),
                       modifiedDate: Date()),
                  Meet(name: "Meet #2",
                       date: Date(),
                       description: "description",
                       address: "address",
                       long: nil,
                       lat: nil,
                       creationDate: Date(),
                       modifiedDate: Date()),
                  Meet(name: "Meet #3",
                       date: Date(),
                       description: "description",
                       address: "address",
                       long: nil,
                       lat: nil,
                       creationDate: Date(),
                       modifiedDate: Date()),
                  Meet(name: "Meet #4",
                       date: Date(),
                       description: "description",
                       address: "address",
                       long: nil,
                       lat: nil,
                       creationDate: Date(),
                       modifiedDate: Date()),
                  Meet(name: "Meet #5",
                       date: Date(),
                       description: "description",
                       address: "address",
                       long: nil,
                       lat: nil,
                       creationDate: Date(),
                       modifiedDate: Date()),
]
